// TODO: Remove once top-level lib.rs enables warnings.
#![warn(warnings)]

use std::collections::HashMap;
use std::collections::HashSet;

use itertools::Itertools;
use typed_arena::Arena;

use prusti_interface::specs::typed;

use crate::encoder::places;
use crate::utils::namespace::Namespace;

mod construct;
mod encode;
mod pledges;
mod display;
mod split_reborrows;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Context {
    BeforeExpiry, AfterUnblocked
}

#[derive(Default)]
pub struct ExpirationToolCarrier<'c, 'tcx> {
    /// A mapping from places to integers that is used to represent places in the Viper encoding.
    place_mapping: HashMap<places::Place<'tcx>, usize>,
    /// Arena for all the expiration tool lists owned by this carrier.
    expiration_tools: Arena<ExpirationTools<'c, 'tcx>>,
    /// Arena for all the expiration tools owned by this carrier.
    expiration_tool: Arena<ExpirationTool<'c, 'tcx>>,
    /// Arena for all the magic wands owned by this carrier.
    magic_wand: Arena<MagicWand<'c, 'tcx>>,
    /// Arena for all the pledges owned by this carrier.
    pledge: Arena<typed::Assertion<'tcx>>
}

/// A collection of expiration tools, one for every connected component of input/output references.
#[derive(Debug, Clone)]
pub struct ExpirationTools<'c, 'tcx> {
    carrier: &'c ExpirationToolCarrier<'c, 'tcx>,
    expiration_tools: Vec<&'c ExpirationTool<'c, 'tcx>>
}

/// This is a high-level representation of the nested magic wands that are returned from a
/// re-borrowing function. It has the same structure as the the corresponding Viper expression, but
/// makes the individual components that make up this expression explicit.
#[derive(Debug, Clone)]
pub struct ExpirationTool<'c, 'tcx> {
    carrier: &'c ExpirationToolCarrier<'c, 'tcx>,
    /// The places that are still blocking something.
    blocking: HashSet<places::Place<'tcx>>,
    /// The places that are still blocked by something.
    blocked: HashSet<places::Place<'tcx>>,
    /// The magic wands that can be used to expire the places in `blocking` and unblock the places
    /// in `blocked`. For every reference `r` of `blocking`, there is a magic wand `magic_wands[r]`
    /// that is used to expire `r`.
    magic_wands: Vec<&'c MagicWand<'c, 'tcx>>,
}

/// This is a high-level representation of a single magic wand as it appears in the expiration
/// tool. It contains the necessary information to build the left- and right-hand side of the
/// concrete magic wand, but conceptually separated to facilitate manipulation.
#[derive(Debug, Clone)]
pub struct MagicWand<'c, 'tcx> {
    carrier: &'c ExpirationToolCarrier<'c, 'tcx>,
    /// The namespace for names generated by this magic wand.
    namespace: Namespace,
    /// The reference that is expired by applying this magic wand. During encoding, permission for
    /// this will place will make up the left-hand side of the magic wand.
    expired: HashSet<places::Place<'tcx>>,
    /// The references that are immediately unblocked by applying this magic wand. During encoding,
    /// permission for these places will appear on the right-hand side of the magic wand.
    unblocked: HashSet<places::Place<'tcx>>,
    /// The pledges that are made available by applying this magic wand. During encoding, they will
    /// be embedded on the right-hand side of the magic wand.
    pledges: Vec<&'c typed::Assertion<'tcx>>,
    /// The expiration tools that can be used to expire further references. During encoding, they
    /// will be included on the right-hand side of the magic wand.
    expiration_tools: &'c ExpirationTools<'c, 'tcx>,
}

impl<'c, 'tcx> ExpirationToolCarrier<'c, 'tcx> {
    fn add_expiration_tools(&'c self,
        expiration_tools: Vec<&'c ExpirationTool<'c, 'tcx>>
    ) -> &'c ExpirationTools<'c, 'tcx> {
        let expiration_tools = ExpirationTools { carrier: self, expiration_tools };
        self.expiration_tools.alloc(expiration_tools)
    }
    fn add_expiration_tool(&'c self,
        blocking: HashSet<places::Place<'tcx>>,
        blocked: HashSet<places::Place<'tcx>>,
        magic_wands: Vec<&'c MagicWand<'c, 'tcx>>
    ) -> &'c ExpirationTool<'c, 'tcx> {
        let expiration_tool = ExpirationTool {
            carrier: self,
            blocking, blocked, magic_wands
        };
        self.expiration_tool.alloc(expiration_tool)
    }
    fn add_magic_wand(&'c self,
        namespace: Namespace,
        expired: HashSet<places::Place<'tcx>>,
        unblocked: HashSet<places::Place<'tcx>>,
        pledges: Vec<&'c typed::Assertion<'tcx>>,
        expiration_tools: &'c ExpirationTools<'c, 'tcx>
    ) -> &'c MagicWand<'c, 'tcx> {
        let magic_wand = MagicWand {
            carrier: self,
            namespace, expired, unblocked, pledges, expiration_tools
        };
        self.magic_wand.alloc(magic_wand)
    }
    fn add_pledge(&'c self, pledge: typed::Assertion<'tcx>) -> &'c typed::Assertion<'tcx> {
        self.pledge.alloc(pledge)
    }
}

impl<'c, 'p, 'tcx: 'p> ExpirationTools<'c, 'tcx> {
    pub fn blocking(&'c self) -> HashSet<&'c places::Place<'tcx>> {
        self.into_iter().flat_map(|et| &et.blocking).collect()
    }

    pub fn blocked(&'c self) -> HashSet<&'c places::Place<'tcx>> {
        self.into_iter().flat_map(|et| &et.blocked).collect()
    }

    /// Give us the expiration tools that represent the state after all the given places have
    /// expired.
    pub fn expire(&'c self,
        places: impl IntoIterator<Item=&'p places::Place<'tcx>>
    ) -> &'c ExpirationTools<'c, 'tcx> {
        let mut places = places.into_iter();
        if let Some(place) = places.next() {
            let expiration_tools = self.into_iter().flat_map(|et|
                if let Some(ets) = et.expire(place) {
                    ets.expiration_tools.clone()
                } else {
                    vec![et]
                }
            ).collect();
            self.carrier.add_expiration_tools(expiration_tools)
        } else {
            self
        }
    }

    /// Produces the magic wand that expires the given place.
    pub fn magic_wand(&'c self, place: &'p places::Place<'tcx>) -> Option<&'c MagicWand<'c, 'tcx>> {
        self.into_iter().flat_map(|et| et.magic_wand(place)).next()
    }
}

impl<'c, 'tcx> IntoIterator for &ExpirationTools<'c, 'tcx> {
    type Item = &'c ExpirationTool<'c, 'tcx>;
    type IntoIter = std::vec::IntoIter<&'c ExpirationTool<'c, 'tcx>>;
    fn into_iter(self) -> Self::IntoIter {
        self.expiration_tools.clone().into_iter()
    }
}

impl<'c, 'p, 'tcx: 'p> ExpirationTool<'c, 'tcx> {
    /// Creates an iterator over all magic wands that is ordered deterministically. This is
    /// important during the encoding, where the order of conjuncts in magic wands matters.
    fn magic_wands(&self) -> impl Iterator<Item=&'c MagicWand<'c, 'tcx>> {
        self.magic_wands.iter().map(|mw| *mw).sorted_by_key(|mw| mw.expired())
    }

    fn magic_wand(&'c self,
        place: &'p places::Place<'tcx>
    ) -> Option<&'c MagicWand<'c, 'tcx>> {
        self.magic_wands().filter(|mw| mw.expired() == place).next()
    }

    fn expire(&'c self,
        place: &'p places::Place<'tcx>
    ) -> Option<&'c ExpirationTools<'c, 'tcx>> {
        self.magic_wand(place).map(|mw| mw.expiration_tools)
    }
}

impl<'c, 'tcx> MagicWand<'c, 'tcx> {
    /// Returns the reference that is expired by this magic wand. If there is more than one such
    /// reference, it panics.
    pub fn expired(&self) -> &places::Place<'tcx> {
        assert_eq!(self.expired.len(), 1);
        self.expired.iter().next().unwrap()
    }

    /// Creates an iterator over all unblocked references that is ordered deterministically. This
    /// is important during the encoding, where the order of conjuncts in magic wands matters.
    pub fn unblocked(&self) -> impl Iterator<Item=&places::Place<'tcx>> {
        self.unblocked.iter().sorted()
    }

    /// Creates an iterator over all pledges that is ordered deterministically. This is important
    /// during the encoding, where the order of conjuncts in magic wands matters.
    pub fn pledges(&self) -> impl Iterator<Item=&'c typed::Assertion<'tcx>> {
        // TODO: This is not determinisitc yet.
        self.pledges.clone().into_iter()
    }

    /// Creates an iterator over all expiration tools that is ordered deterministically. This is
    /// important during the encoding, where the order of conjuncts in magic wands matters.
    pub fn expiration_tools(&self) -> impl Iterator<Item=&'c ExpirationTool<'c, 'tcx>> {
        self.expiration_tools.into_iter().sorted_by_key(|et| et.blocking.iter().min())
    }
}
